#!/usr/bin/env python3
"""mint_tool.py — Regenerate toolbox artifacts from tools.md.

Reads ~/projects/claf/toolbox/tools.md and generates:
  - registry.json
  - Missing Python module stubs
  - Charter mappings in ~/projects/claf/charter/charter_core.md

Usage:
  python3 ~/projects/claf/toolbox/mint_tool.py [--dry-run]
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

TOOLBOX_DIR = Path.home() / "projects" / "claf" / "toolbox"
CHARTER_PATH = Path.home() / "projects" / "claf" / "charter" / "charter_core.md"
TOOLS_MD = TOOLBOX_DIR / "tools.md"

MARKER_START = "<!-- TOOLBOX MAPPINGS START"
MARKER_END = "<!-- TOOLBOX MAPPINGS END -->"
RUN_TOOL = "python3 ~/projects/claf/toolbox/run_tool.py"


def parse_tools(path: Path) -> list[dict]:
    text = path.read_text(encoding="utf-8")
    tools = []
    current = None

    for line in text.splitlines():
        heading = re.match(r"^##\s+(\S+)", line)
        if heading:
            if current:
                tools.append(current)
            current = {"name": heading.group(1).strip()}
            continue

        if current is None:
            continue

        m = re.match(r"-\s+\*\*([^*]+?)\*\*\s*(.*)", line)
        if m:
            key = m.group(1).rstrip(":").lower().strip()
            value = m.group(2).strip()
            # A tool may declare multiple `example:` lines — collect them.
            if key == "example":
                current.setdefault("example", []).append(value)
            else:
                current[key] = value

    if current:
        tools.append(current)
    return tools


def parse_args(args_line: str) -> list[dict]:
    if not args_line or args_line.lower() == "(none)":
        return []

    parsed = []
    for part in re.split(r",\s*(?=[a-zA-Z_]+\s*\()", args_line):
        part = part.strip()
        if not part:
            continue
        m = re.match(r"(\w+)\s*\(\s*(\w+)\s*,\s*(\w+)\s*\)", part)
        if m:
            parsed.append(
                {
                    "name": m.group(1),
                    "type": m.group(2),
                    "required": m.group(3).lower() == "required",
                }
            )
    return parsed


def infer_category(tool: dict) -> str:
    module = tool.get("module", "")
    desc = tool.get("description", "").lower()
    if "browser" in desc or "chrome" in desc or "website" in desc or "url" in desc:
        return "browser"
    if "email" in desc or "thunderbird" in desc:
        return "email"
    if "shell" in desc or "command" in desc:
        return "shell"
    return "shell"


def build_registry(tools: list[dict]) -> dict:
    entries = []
    for tool in tools:
        commands = [c.strip() for c in tool.get("command", "").split("|") if c.strip()]
        entries.append(
            {
                "name": tool["name"],
                "enabled": True,
                "category": infer_category(tool),
                "requires_approval": False,
                "requires_credentials": False,
                "description": tool.get("description", ""),
                # Trigger phrases — consumed by the router (_matches_toolbox_command)
                # to pin matching requests to LOCAL so a toolbox tool never escalates.
                "commands": commands,
            }
        )
    return {"tools": entries}


def json_template(args: list[dict]) -> str:
    if not args:
        return "{}"
    obj = {a["name"]: f"<{a['name']}>" for a in args}
    return json.dumps(obj)


def build_charter_lines(tools: list[dict]) -> list[str]:
    lines = [f"{MARKER_START} — generated by mint_tool.py -->"]
    for tool in tools:
        commands = tool.get("command", tool["name"])
        args = parse_args(tool.get("args", ""))
        template = json_template(args)
        line = f"- {commands} → Bash: {RUN_TOOL} {tool['name']} '{template}'"
        if tool.get("never"):
            line += f" [NEVER: {tool['never']}]"
        lines.append(line)
        examples = tool.get("example")
        if isinstance(examples, str):
            examples = [examples]
        for ex in examples or []:
            lines.append(f"  EXAMPLE: {ex}")
    lines.append(MARKER_END)
    return lines


def module_stub(tool: dict) -> str:
    name = tool["name"]
    args = parse_args(tool.get("args", ""))
    arg_names = [a["name"] for a in args]
    if arg_names:
        arg_block = "\n".join(f"    {n} = args.get('{n}')" for n in arg_names)
    else:
        arg_block = "    pass"
    return f'''#!/usr/bin/env python3
"""Minted tool: {name}.

{tool.get("description", "")}
"""


def run(args: dict | None = None) -> str:
    args = args or {{}}
{arg_block}
    # TODO: implement
    return f"[tool result] {name} executed with {{args}}"
'''


def update_charter(tools: list[dict], dry_run: bool) -> str:
    lines = CHARTER_PATH.read_text(encoding="utf-8").splitlines()
    generated = build_charter_lines(tools)

    start_idx = None
    end_idx = None
    for i, line in enumerate(lines):
        if line.strip().startswith(MARKER_START):
            start_idx = i
        elif line.strip().startswith(MARKER_END):
            end_idx = i
            break

    if start_idx is not None and end_idx is not None:
        new_lines = lines[:start_idx] + generated + lines[end_idx + 1 :]
    else:
        # Insert after the static KNOWN COMMANDS block (before IDENTITY)
        identity_idx = None
        for i, line in enumerate(lines):
            if line.strip() == "IDENTITY":
                identity_idx = i
                break
        insert_idx = identity_idx if identity_idx is not None else len(lines)
        new_lines = lines[:insert_idx] + [""] + generated + [""] + lines[insert_idx:]

    new_text = "\n".join(new_lines) + "\n"
    if dry_run:
        return new_text
    CHARTER_PATH.write_text(new_text, encoding="utf-8")
    return new_text


def ensure_modules(tools: list[dict], dry_run: bool) -> list[str]:
    created = []
    for tool in tools:
        module_name = tool.get("module", f"{tool['name']}.py")
        if not module_name.endswith(".py"):
            module_name += ".py"
        path = TOOLBOX_DIR / module_name
        if not path.exists():
            if not dry_run:
                path.write_text(module_stub(tool), encoding="utf-8")
            created.append(str(path))
    return created


def main() -> int:
    parser = argparse.ArgumentParser(description="Regenerate toolbox artifacts")
    parser.add_argument("--dry-run", action="store_true", help="Print changes without writing")
    args = parser.parse_args()

    if not TOOLS_MD.exists():
        print(f"[mint error] {TOOLS_MD} not found", file=sys.stderr)
        return 1

    tools = parse_tools(TOOLS_MD)
    if not tools:
        print("[mint] No tools found in tools.md", file=sys.stderr)
        return 0

    registry = build_registry(tools)
    if args.dry_run:
        print("=== registry.json ===")
        print(json.dumps(registry, indent=2))
        print("\n=== charter mappings ===")
        print("\n".join(build_charter_lines(tools)))
    else:
        (TOOLBOX_DIR / "registry.json").write_text(
            json.dumps(registry, indent=2) + "\n", encoding="utf-8"
        )
        created = ensure_modules(tools, dry_run=False)
        update_charter(tools, dry_run=False)
        print(f"[mint] {len(tools)} tool(s) registered.")
        if created:
            for c in created:
                print(f"[mint] created stub: {c}")
        print(f"[mint] updated {CHARTER_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
